spring.application.name=campusFlow

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/campusflow?createDatabaseIfNotExist=true&serverTimezone=America/Bogota}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.price-pago-unico=${STRIPE_PRICE_PAGO_UNICO}
stripe.price-plan-individual=${STRIPE_PRICE_PLAN_INDIVIDUAL}
stripe.url-exito=${URL_EXITO:http://localhost:8080/pago-exitoso}
stripe.url-cancelado=${URL_CANCELADO:http://localhost:8080/pago-cancelado}